<?php
$_MENU = array(
    array( 'page'=>'INICIO', 'slug'=> 'index', 'link'=> 'index', 'description'=>'IQmax - INTELIGENCIA AL MÁXIMO. Sistema Avanzado de Lectura Integral para Niños, Adolescentes y Adultos. Lee miles de palabras por minuto. Mejora tu concentración y comprensión de lectura. Mejora tus hábitos de lectura. Técnicas de estudio para facilitar el aprendizaje para estudiantes y profesionales. La Paz. Santa Cruz. Cochabamba. Oruro. Bolivia', 'title'=>'IQmax - INTELIGENCIA AL MÁXIMO | Sistema Avanzado de Lectura Integral para Niños, Adolescentes y Adultos | Lee miles de palabras por minuto | Mejora tu concentración y comprensión de lectura | Hábitos de lectura | LA PAZ | SANTA CRUZ | COCHABAMBA | ORURO | BOLIVIA', 'keywords'=>'citex, citex bolivia, talentos para la excelencia, sistema avanzado de lectura integral, sistema avanzado de lectura integral para niños, sistema avanzado de lectura integral para adolescentes, sistema avanzado de lectura integral para adultos, metodo de aprendizaje para escolares, metodo de aprendizaje para estudiantes, metodo de aprendizaje para profesionales, lee mil palabras por minuto, mejora tu concentracion, mejora tu comprension, habitos de lectura, lee 10 veces mas rapido, tecnicas de estudio, leer mas rapido, tecnicas de lectura rapida, La Paz, Cochabamba, Santa Cruz, Oruro, Bolivia, CITEX BOLIVIA, CITEX LA PAZ, CITEX COCHABAMBA, CITEX SANTA CRUZ, CITEX ORURO' ),
    array( 'page'=> 'CONÓCENOS', 'slug'=>'conocenos', 'link'=> 'conocenos', 'description'=>'CON&Oacute;CENOS - IQmax - INTELIGENCIA AL MÁXIMO. Sistema Avanzado de Lectura Integral para Ni&ntilde;os, Adolescentes y Adultos. Lee miles de palabras por minuto. Mejora tu concentraci&oacute;n y comprensi&oacute;n de lectura. Mejora tus h&aacute;bitos de lectura. T&eacute;cnicas de estudio para facilitar el aprendizaje para estudiantes y profesionales. La Paz. Santa Cruz. Cochabamba. Oruro. Bolivia', 'title'=>'CONÓCENOS - IQmax - INTELIGENCIA AL MÁXIMO | Sistema Avanzado de Lectura Integral para Ni&ntilde;os, Adolescentes y Adultos | Lee miles de palabras por minuto | Mejora tu concentración y comprensión de lectura | H&aacute;bitos de lectura | LA PAZ | SANTA CRUZ | COCHABAMBA | ORURO | BOLIVIA', 'keywords'=>'citex, citex bolivia, talentos para la excelencia, sistema avanzado de lectura integral, sistema avanzado de lectura integral para ni&ntilde;os, sistema avanzado de lectura integral para adolescentes, sistema avanzado de lectura integral para adultos, metodo de aprendizaje para escolares, metodo de aprendizaje para estudiantes, metodo de aprendizaje para profesionales, lee mil palabras por minuto, mejora tu concentracion, mejora tu comprension, habitos de lectura, lee 10 veces mas rapido, tecnicas de estudio, leer mas rapido, tecnicas de lectura rapida, La Paz, Cochabamba, Santa Cruz, Oruro, Bolivia, CITEX BOLIVIA, CITEX LA PAZ, CITEX COCHABAMBA, CITEX SANTA CRUZ, CITEX ORURO' ),
    array( 'page'=> 'LOS PROGRAMAS', 'slug'=> 'programas', 'link'=> 'programas', 'description'=>'LOS PROGRAMAS - IQmax - INTELIGENCIA AL MÁXIMO. Sistema Avanzado de Lectura Integral para Ni&ntilde;os, Adolescentes y Adultos. Lee miles de palabras por minuto. Mejora tu concentraci&oacute;n y comprensi&oacute;n de lectura. Mejora tus h&aacute;bitos de lectura. T&eacute;cnicas de estudio para facilitar el aprendizaje para estudiantes y profesionales. La Paz. Santa Cruz. Cochabamba. Oruro. Bolivia', 'title'=>'LOS PROGRAMAS - IQmax - INTELIGENCIA AL MÁXIMO | Sistema Avanzado de Lectura Integral para Ni&ntilde;os, Adolescentes y Adultos | Lee miles de palabras por minuto | Mejora tu concentraci&oacute;n y comprensi&oacute;n de lectura | H&aacute;bitos de lectura | LA PAZ | SANTA CRUZ | COCHABAMBA | ORURO | BOLIVIA', 'keywords'=>'citex, citex bolivia, talentos para la excelencia, sistema avanzado de lectura integral, sistema avanzado de lectura integral para ni&ntilde;os, sistema avanzado de lectura integral para adolescentes, sistema avanzado de lectura integral para adultos, metodo de aprendizaje para escolares, metodo de aprendizaje para estudiantes, metodo de aprendizaje para profesionales, lee mil palabras por minuto, mejora tu concentracion, mejora tu comprension, habitos de lectura, lee 10 veces mas rapido, tecnicas de estudio, leer mas rapido, tecnicas de lectura rapida, La Paz, Cochabamba, Santa Cruz, Oruro, Bolivia, CITEX BOLIVIA, CITEX LA PAZ, CITEX COCHABAMBA, CITEX SANTA CRUZ, CITEX ORURO' ),
    array( 'page'=> 'TEST', 'slug'=> 'test', 'link'=> 'test', 'description'=>'IQmax - INTELIGENCIA AL MÁXIMO. Tests Interactivos para medir velocidad de lectura, comprensión y habilidades', 'title'=>'IQmax - INTELIGENCIA AL MÁXIMO | Tests Interactivos para medir velocidad de lectura, comprensión y habilidades', 'keywords'=>'citex, citex bolivia, talentos para la excelencia, tests interactivos, mide tu velocidad de lectura, mide tu nivel de rendimiento, mide tus habilidades, mejora rendimiento, mejora eficiencia, lectura veloz, sistema avanzado de lectura integral, sistema avanzado de lectura integral para niños, sistema avanzado de lectura integral para adolescentes, sistema avanzado de lectura integral para adultos, metodo de aprendizaje para escolares, metodo de aprendizaje para estudiantes, metodo de aprendizaje para profesionales, lee mil palabras por minuto, mejora tu concentracion, mejora tu comprension, habitos de lectura, lee 10 veces mas rapido, tecnicas de estudio, leer mas rapido' ),
    array( 'page'=>'RANKING', 'slug'=> 'ranking', 'link'=> 'ranking', 'description'=>'RANKING - IQmax - INTELIGENCIA AL MÁXIMO. Sistema Avanzado de Lectura Integral para Ni&ntilde;os, Adolescentes y Adultos. Lee miles de palabras por minuto. Mejora tu concentraci&oacute;n y comprensi&oacute;n de lectura. Mejora tus h&aacute;bitos de lectura. T&eacute;cnicas de estudio para facilitar el aprendizaje para estudiantes y profesionales. La Paz. Santa Cruz. Cochabamba. Oruro. Bolivia', 'title'=>'RANKING - IQmax - INTELIGENCIA AL MÁXIMO | Sistema Avanzado de Lectura Integral para Ni&ntilde;os, Adolescentes y Adultos | Lee miles de palabras por minuto | Mejora tu concentracioacute;n y comprensioacute;n de lectura', 'keywords'=>'citex, citex bolivia, talentos para la excelencia, sistema avanzado de lectura integral, sistema avanzado de lectura integral para ni&ntilde;os, sistema avanzado de lectura integral para adolescentes, sistema avanzado de lectura integral para adultos, metodo de aprendizaje para escolares, metodo de aprendizaje para estudiantes, metodo de aprendizaje para profesionales, lee mil palabras por minuto, mejora tu concentracion, mejora tu comprension, habitos de lectura, lee 10 veces mas rapido, tecnicas de estudio, leer mas rapido, tecnicas de lectura rapida, La Paz, Cochabamba, Santa Cruz, Oruro, Bolivia, CITEX BOLIVIA, CITEX LA PAZ, CITEX COCHABAMBA, CITEX SANTA CRUZ, CITEX ORURO' ),
    array( 'page'=>'BLOG', 'slug'=> 'blog', 'link'=> 'blog', 'description'=>'BLOG - IQmax - INTELIGENCIA AL MÁXIMO. Sistema Avanzado de Lectura Integral para Ni&ntilde;os, Adolescentes y Adultos. Lee miles de palabras por minuto. Mejora tu concentraci&oacute;n y comprensi&oacute;n de lectura. Mejora tus h&aacute;bitos de lectura. T&eacute;cnicas de estudio para facilitar el aprendizaje para estudiantes y profesionales. La Paz. Santa Cruz. Cochabamba. Oruro. Bolivia', 'title'=>'BLOG - IQmax - INTELIGENCIA AL MÁXIMO | Sistema Avanzado de Lectura Integral para Ni&ntilde;os, Adolescentes y Adultos', 'keywords'=>'citex, citex bolivia, talentos para la excelencia, sistema avanzado de lectura integral, sistema avanzado de lectura integral para ni&ntilde;os, sistema avanzado de lectura integral para adolescentes, sistema avanzado de lectura integral para adultos, metodo de aprendizaje para escolares, metodo de aprendizaje para estudiantes, metodo de aprendizaje para profesionales, lee mil palabras por minuto, mejora tu concentracion, mejora tu comprension, habitos de lectura, lee 10 veces mas rapido, tecnicas de estudio, leer mas rapido, tecnicas de lectura rapida, La Paz, Cochabamba, Santa Cruz, Oruro, Bolivia, CITEX BOLIVIA, CITEX LA PAZ, CITEX COCHABAMBA, CITEX SANTA CRUZ, CITEX ORURO' ),
    array( 'page'=>'TÉRMINOS Y CONDICIONES', 'slug'=> 'terminos-condiciones', 'link'=> 'terminos-condiciones', 'description'=>'TÉRMINOS Y CONDICIONES - IQmax - INTELIGENCIA AL MÁXIMO. Sistema Avanzado de Lectura Integral para Ni&ntilde;os, Adolescentes y Adultos.', 'title'=>'TÉRMINOS Y CONDICIONES - IQmax - INTELIGENCIA AL MÁXIMO | Sistema Avanzado de Lectura Integral para Ni&ntilde;os, Adolescentes y Adultos', 'keywords'=>'', 'topMenu'=>'no' ),
    array( 'page'=>'CONTACTO', 'slug'=> 'contacto', 'link'=> 'contacto', 'description'=>'CONTACTO - IQmax - INTELIGENCIA AL MÁXIMO. Sistema Avanzado de Lectura Integral para Ni&ntilde;os, Adolescentes y Adultos. Lee miles de palabras por minuto. Mejora tu concentraci&oacute;n y comprensi&oacute;n de lectura. Mejora tus h&aacute;bitos de lectura. T&eacute;cnicas de estudio para facilitar el aprendizaje para estudiantes y profesionales. La Paz. Santa Cruz. Cochabamba. Oruro. Bolivia', 'title'=>'CONTACTO - IQmax - INTELIGENCIA AL MÁXIMO | Sistema Avanzado de Lectura Integral para Ni&ntilde;os, Adolescentes y Adultos | Lee miles de palabras por minuto | Mejora tu concentraci&oacute;n y comprensi&oacute;n de lectura | Hábitos de lectura | LA PAZ | SANTA CRUZ | COCHABAMBA | ORURO | BOLIVIA', 'keywords'=>'citex, citex bolivia, talentos para la excelencia, sistema avanzado de lectura integral, sistema avanzado de lectura integral para ni&ntilde;os, sistema avanzado de lectura integral para adolescentes, sistema avanzado de lectura integral para adultos' ),
    array( 'page'=>'A LEER BOLIVIA', 'slug'=> 'a-leer-bolivia', 'link'=> 'a-leer-bolivia', 'description'=>'A LEER BOLIVIA - IQmax - INTELIGENCIA AL MÁXIMO. Únete a nuestra revolucionaria iniciativa que busca encender la pasión por la lectura en los corazones de los estudiantes de Bolivia. A través de un concurso intercolegial, inspiramos a los niños a explorar mundos de conocimiento y creatividad. Este es tu momento para contribuir a un cambio educativo significativo.', 'title'=>'A LEER BOLIVIA - IQmax - INTELIGENCIA AL MÁXIMO | Sistema Avanzado de Lectura Integral para Ni&ntilde;os, Adolescentes y Adultos | Lee miles de palabras por minuto | Mejora tu concentraci&oacute;n y comprensi&oacute;n de lectura | Hábitos de lectura | LA PAZ | SANTA CRUZ | COCHABAMBA | ORURO | BOLIVIA', 'keywords'=>'A LEER BOLIVIA, citex, citex bolivia, talentos para la excelencia, sistema avanzado de lectura integral, sistema avanzado de lectura integral para ni&ntilde;os, sistema avanzado de lectura integral para adolescentes, sistema avanzado de lectura integral para adultos' ) );
    
    
$_SOCIAL_URL = array(
    'instagram' => 'https://www.instagram.com/iqmaximo/',
    'facebook' => 'https://www.facebook.com/IQmaximo',
    'twitter' => 'https://twitter.com/IQmaximo',
    'youtube' => 'https://www.youtube.com/channel/UCd7TzLXg1uXNtQqd1oYOGfA',
);
 
$_CONTACT = array(
    'phone' => '(+591) 73 6000 60',
    'email' => 'info@iqmaximo.com',
    'whatsapp' => 'https://api.whatsapp.com/send?phone=59173600060&text=Hola%2C%20quiero%20que%20se%20contacten%20conmigo%20para%20recibir%20información'
);

?>